apiVersion: v1
kind: Service
metadata:
  name: devsu-python-service
  namespace: devsu-app
spec:
  type: LoadBalancer
  selector:
    app: devsu-python
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
